### PR TITLE
section_2: update OpenSuse install section to use OSE 3.7

### PR DESCRIPTION
**Pull request by czanik**
Signed-off-by: Peter Czanik peter.czanik@balabit.com

### CODE REVIEW

**Comment by czanik** [comment]
@gregory094 is the target branch okay?

**Comment by justcallmegreg** [comment]
As far as I can see you've modified `chapter_0`. You should send the PR to `chapter_0`.
After changing the branch I'll merge your patches. :+1:

**Comment by lbudai** [comment]
@czanik : could you rebase this branch?
[ It is an old PR, we missed it somehow, sorry. ]

**Comment by lbudai** [comment]
@czanik : so, will you rebase it?

**Comment by czanik** [comment]
@lbudai : no. Sorry, but I don't know git enough.

**Comment by lbudai** [comment]
@czanik : if you need help in git, we can help you.
I think we should extend the content available in our gitbook and the fact that we are using git should not block this activity.

**Comment by bazsi** [comment]
$ git rebase -i origin/master

Patches will be replayed, conflicts highlighted as they happen.

After resolving a conflict:
$ git add filename
$ git rebase --cont

**Pull request closed without merging**
