### PR TITLE
Docker: added new chapter to describe docker images for syslog-ng

### PR DESCRIPTION
**Pull request by mitzkia**
Signed-off-by: Andras Mitzki mitzkia@gmail.com

### CODE REVIEW

**Comment by bazsi** [comment]
Can the syslog-ng-dev image also compile deb packages? It should be documented if so.

**Comment by mitzkia** [comment]
Sorry, maybe it was misunderstood from the description. 
syslog-ng-dev and syslog-ng-incubator-dev images can not compile deb packages, they only can compile syslog-ng from source. 
What do you think should I complete the description with this information?

**Comment by lbudai** [comment]
Hi,

I think we can easily add such a feature...

**Comment by bazsi** [comment]
I am not pushing that. I was jus curious, lets wait until people start
using this and ask questions.

Do we have usage statistics?

**Comment by lbudai** [comment]
Yeah, I know , but testing the deb packaging scripts could be useful before uploading it to obs... Or just create the deb source in a docker image.

**Comment by bazsi** [comment]
That was my idea as well. That's why I asked. I thought this docker image
was also used for that purpose. It is probably also useful to check if the
docker image indeed works.

**Comment by ihrwein** [comment]
I think the main documentation page for the Docker images is their repository on Docker Hub. I wouldn't copy those docs here because we have to maintain the same information in two places. 

So what I'd do:
- create only one main chapter (like your `chapter_6`)
- listen the available images with some useful description (like you did)
- link the Docker Hub pages in the image description

Before you make this changes I'd ask the opinion of the others (@gregory094, @lbudai, ...) because we live in democracy :)

**Comment by mitzkia** [comment]
PR has changed.
As we discussed with @ihrwein and @gregory094 I modified the content of this chapter. It will only contain a short introduction to syslog-ng docker images, and it will also contain a GitHub and Docker Hub URLs for a detailed description. 

@bazsi , yes we can check the usage statistics from docker hub. 
The current status is:

```
balabit/syslog-ng - 23 pulls
balabit/syslog-ng-dev - 7 pulls
balabit/syslog-ng-incubator-dev - 1 pulls
```

**Comment by ihrwein** [comment]
My review notes are opinionated so I need somebody else make a decision.
1. I'd use flow text instead of enumerations where you describe an image. An example:

Instead of this:

```
 * Within this docker image syslog-ng and syslog-ng incubator is installed from deb package.
 * It is intended to be used as a system logging service.
```

I'd write (with some rephrases, IMHO users aren't interested in how syslog-ng is installed):

```
syslog-ng and syslog-ng-incubator are installed in this Docker image so you can use it as a system logging service.
For more information please check the image on Docker Hub: https://hub.docker.com/r/balabit/syslog-ng/
```
1. I'd place the Docker Hub link after every description (like above) and we don't need the following lines:

```
+### Availability and description of docker images
+
+#### Place of docker images
+* https://hub.docker.com/r/balabit/
```
1. The word `Docker` starts with a big `D` (unfortunately there is no `EKH` letter in it :()
2. The last section (Source project...) as good as it is :)

**Comment by lbudai** [comment]
Hi,

@ihrwein : I think it's not a big issue if we mention this installation info...
I can imagine that this is intereting info for someone. But it is also true that it can be easily checked by anyone in the docker file...

Why would you prefer adding the link after every description ? (just a question )

[anyway, I add my :+1:  here, it is good enough I think ]

**Comment by ihrwein** [comment]
thanks :smile:

**Comment by ihrwein** [comment]
@gregory094 : where should we merge this? It's a new chapter.

**Comment by justcallmegreg** [comment]
We've `chapter_6` branch now... somehow we should send this PR to that branch.

**Comment by mitzkia** [comment]
I create a new PR #50 from this patch to a newly created chapter_6 branch.
I think we can close this PR.

**Pull request closed without merging**
